/* ═══════════════════════════════════════════════════════════
   KIXIKILA MARKET — data.js
   Dados: Categorias e Produtos Angolanos
═══════════════════════════════════════════════════════════ */

const CATEGORIES = [
  { id: 'all',         name: 'Todos',        icon: '🏪', count: 20 },
  { id: 'alimentacao', name: 'Alimentação',   icon: '🥘', count: 7  },
  { id: 'bebidas',     name: 'Bebidas',       icon: '🍺', count: 3  },
  { id: 'artesanato',  name: 'Artesanato',    icon: '🪘', count: 3  },
  { id: 'agricultura', name: 'Agricultura',   icon: '🌿', count: 2  },
  { id: 'cosmetica',   name: 'Cosmética',     icon: '💆', count: 2  },
  { id: 'textil',      name: 'Têxtil',        icon: '👗', count: 2  },
  { id: 'tecnologia',  name: 'Tecnologia',    icon: '📱', count: 1  },
];

const PRODUCTS = [
  {
    id: 1,
    name: 'Café Angolano Premium',
    category: 'alimentacao',
    icon: '☕',
    price: 4500,
    oldPrice: 5500,
    badge: 'promo',
    desc: 'Café 100% arábica cultivado nas terras altas do Huambo, torrado artesanalmente. Aroma intenso, sabor encorpado e acidez equilibrada. Um dos melhores cafés de África.',
    origin: 'Huambo',
    rating: 4.9,
    reviews: 128,
  },
  {
    id: 2,
    name: 'Mel Puro do Planalto',
    category: 'alimentacao',
    icon: '🍯',
    price: 6800,
    oldPrice: null,
    badge: 'new',
    desc: 'Mel 100% natural e orgânico, colhido nos apiários das terras altas angolanas. Rico em vitamina C, antioxidantes e propriedades medicinais.',
    origin: 'Bié',
    rating: 4.8,
    reviews: 74,
  },
  {
    id: 3,
    name: 'Cerveja Cuca Original',
    category: 'bebidas',
    icon: '🍺',
    price: 1200,
    oldPrice: null,
    badge: null,
    desc: 'A cerveja mais icónica de Angola. Produzida desde 1952, com um sabor refrescante e inconfundível que atravessa gerações.',
    origin: 'Luanda',
    rating: 4.7,
    reviews: 312,
  },
  {
    id: 4,
    name: 'Sumo de Múcua Natural',
    category: 'bebidas',
    icon: '🧃',
    price: 950,
    oldPrice: null,
    badge: 'new',
    desc: 'Sumo extraído do fruto do baobá angolano. Super rico em vitamina C (6x mais que a laranja), cálcio e fibra. 100% natural, sem conservantes.',
    origin: 'Malanje',
    rating: 4.6,
    reviews: 56,
  },
  {
    id: 5,
    name: 'Máscara Tradicional Cokwe',
    category: 'artesanato',
    icon: '🎭',
    price: 35000,
    oldPrice: null,
    badge: null,
    desc: 'Máscara esculpida à mão por artesãos Cokwe do Moxico. Cada peça é única, feita em madeira local com pigmentos naturais. Autêntica arte angolana.',
    origin: 'Moxico',
    rating: 5.0,
    reviews: 22,
  },
  {
    id: 6,
    name: 'Cesta Artesanal de Palmeira',
    category: 'artesanato',
    icon: '🧺',
    price: 8500,
    oldPrice: 10000,
    badge: 'promo',
    desc: 'Cesta tradicional tecida à mão com folhas de palmeira. Ideal para decoração, mercado ou presente. Durável e biodegradável.',
    origin: 'Benguela',
    rating: 4.5,
    reviews: 88,
  },
  {
    id: 7,
    name: 'Óleo de Palma Vermelho',
    category: 'agricultura',
    icon: '🫙',
    price: 3200,
    oldPrice: null,
    badge: null,
    desc: 'Óleo de palma extraído a frio, 100% natural. Essencial na culinária angolana para a moamba de galinha e outros pratos tradicionais. Rico em vitamina A e E.',
    origin: 'Cabinda',
    rating: 4.7,
    reviews: 145,
  },
  {
    id: 8,
    name: 'Farinha de Mandioca (Fuba)',
    category: 'alimentacao',
    icon: '🌾',
    price: 2400,
    oldPrice: null,
    badge: null,
    desc: 'Farinha de mandioca de alta qualidade para preparar o funge, prato base da gastronomia angolana. Textura fina, sem grumos, seca e bem processada.',
    origin: 'Uíge',
    rating: 4.6,
    reviews: 203,
  },
  {
    id: 9,
    name: 'Capulana Tradicional',
    category: 'textil',
    icon: '🧣',
    price: 7500,
    oldPrice: 9000,
    badge: 'promo',
    desc: 'Pano capulana com padrões tradicionais angolanos em cores vibrantes. 100% algodão, 2m × 1.1m. Usado em trajes, acessórios e decoração.',
    origin: 'Luanda',
    rating: 4.8,
    reviews: 167,
  },
  {
    id: 10,
    name: 'Manteiga de Karité Pura',
    category: 'cosmetica',
    icon: '🧴',
    price: 5500,
    oldPrice: null,
    badge: 'new',
    desc: 'Manteiga de karité não refinada, produzida no Kuando Kubango. Hidratante profundo para pele e cabelo. Sem aditivos químicos, 100% natural.',
    origin: 'Kuando Kubango',
    rating: 4.9,
    reviews: 91,
  },
  {
    id: 11,
    name: 'Ngola Smartphone 4G',
    category: 'tecnologia',
    icon: '📱',
    price: 85000,
    oldPrice: 95000,
    badge: 'promo',
    desc: 'Smartphone assembado em Angola. Ecrã 6.5" HD+, câmara tripla 48MP, bateria 5000mAh, 4G LTE, 128GB. Garantia de 1 ano.',
    origin: 'Luanda',
    rating: 4.3,
    reviews: 44,
  },
  {
    id: 12,
    name: 'Pimenta Angolana Moída',
    category: 'alimentacao',
    icon: '🌶️',
    price: 1800,
    oldPrice: null,
    badge: null,
    desc: 'Pimenta seca e moída de variedades locais, cultivadas no interior de Angola. Picante, aromática e essencial para o jindungo e outros molhos tradicionais.',
    origin: 'Huíla',
    rating: 4.5,
    reviews: 178,
  },
  {
    id: 13,
    name: 'Sabonete Artesanal de Coco',
    category: 'cosmetica',
    icon: '🧼',
    price: 1500,
    oldPrice: 2000,
    badge: 'promo',
    desc: 'Sabonete feito à mão com óleo de coco angolano. Limpa suavemente, hidrata e deixa a pele macia. Sem parabenos nem sulfatos. Aroma natural de coco.',
    origin: 'Namibe',
    rating: 4.7,
    reviews: 134,
  },
  {
    id: 14,
    name: 'Jinguba Torrada e Salgada',
    category: 'alimentacao',
    icon: '🥜',
    price: 2200,
    oldPrice: null,
    badge: null,
    desc: 'Amendoim angolano (jinguba) torrado e salgado artesanalmente. O snack favorito de todo angolano! Crocante, saboroso e rico em proteínas.',
    origin: 'Cuando Cubango',
    rating: 4.8,
    reviews: 287,
  },
  {
    id: 15,
    name: 'Tecido Bazin Bordado',
    category: 'textil',
    icon: '👘',
    price: 15000,
    oldPrice: null,
    badge: 'new',
    desc: 'Tecido bazin premium com bordados feitos em Angola. Ideal para trajes de cerimónia e casamentos tradicionais. Várias cores disponíveis.',
    origin: 'Luanda',
    rating: 4.9,
    reviews: 38,
  },
  {
    id: 16,
    name: 'Vinho de Palma (Marufo)',
    category: 'bebidas',
    icon: '🥥',
    price: 800,
    oldPrice: null,
    badge: null,
    desc: 'Vinho de palma tradicional angolano, colhido das palmeiras locais. Bebida refrescante com sabor levemente ácido e doce. Consumir fresco.',
    origin: 'Bengo',
    rating: 4.4,
    reviews: 62,
  },
  {
    id: 17,
    name: 'Sementes de Moringa',
    category: 'agricultura',
    icon: '🌿',
    price: 2800,
    oldPrice: null,
    badge: 'new',
    desc: 'Sementes de moringa angolana, a "árvore da vida". Ricas em vitaminas A, C, E, cálcio e proteínas. Ideais para chá, pó alimentar e óleo.',
    origin: 'Malanje',
    rating: 4.6,
    reviews: 49,
  },
  {
    id: 18,
    name: 'Bombom de Cajú',
    category: 'alimentacao',
    icon: '🍬',
    price: 3500,
    oldPrice: 4000,
    badge: 'promo',
    desc: 'Bombons artesanais feitos com cajú angolano caramelizado. Produto 100% angolano, perfeito para presentes e sobremesas especiais.',
    origin: 'Zaire',
    rating: 4.8,
    reviews: 93,
  },
  {
    id: 19,
    name: 'Estatueta de Ébano',
    category: 'artesanato',
    icon: '🗿',
    price: 22000,
    oldPrice: null,
    badge: null,
    desc: 'Estatueta esculpida à mão em madeira de ébano. Representa figuras tradicionais angolanas. Cada peça é única e assinada pelo artesão.',
    origin: 'Lunda Norte',
    rating: 4.9,
    reviews: 17,
  },
  {
    id: 20,
    name: 'Ginguba Frita com Mel',
    category: 'alimentacao',
    icon: '🍯',
    price: 2900,
    oldPrice: null,
    badge: 'new',
    desc: 'Amendoim frito caramelizado com mel angolano puro. Combinação irresistível de doce e salgado. Produzido artesanalmente em Luanda.',
    origin: 'Luanda',
    rating: 4.7,
    reviews: 71,
  },
];
