<?php
/* ═══════════════════════════════════════════════════════════
   KIXIKILA MARKET — data.php
   Dados: Categorias e Produtos Angolanos
   (Simulando Base de Dados)
═══════════════════════════════════════════════════════════ */

$CATEGORIES = [
    ['id' => 'all',         'name' => 'Todos',        'icon' => 'store',      'count' => 20],
    ['id' => 'alimentacao', 'name' => 'Alimentação',   'icon' => 'utensils',   'count' => 7],
    ['id' => 'bebidas',     'name' => 'Bebidas',       'icon' => 'beer',       'count' => 3],
    ['id' => 'artesanato',  'name' => 'Artesanato',    'icon' => 'palette',    'count' => 3],
    ['id' => 'agricultura', 'name' => 'Agricultura',   'icon' => 'leaf',       'count' => 2],
    ['id' => 'cosmetica',   'name' => 'Cosmética',     'icon' => 'sparkles',   'count' => 2],
    ['id' => 'textil',      'name' => 'Têxtil',        'icon' => 'shirt',      'count' => 2],
    ['id' => 'tecnologia',  'name' => 'Tecnologia',    'icon' => 'smartphone', 'count' => 1],
];

$PRODUCTS = [
    [
        'id' => 1,
        'name' => 'Café Angolano Premium',
        'category' => 'alimentacao',
        'icon' => 'coffee',
        'image' => '', // Espaço para imagem!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        'price' => 4500,
        'oldPrice' => 5500,
        'badge' => 'promo',
        'desc' => 'Café 100% arábica cultivado nas terras altas do Huambo, torrado artesanalmente. Aroma intenso, sabor encorpado e acidez equilibrada.',
        'origin' => 'Huambo',
        'rating' => 4.9,
        'reviews' => 128,
    ],
    [
        'id' => 2,
        'name' => 'Mel Puro do Planalto',
        'category' => 'alimentacao',
        'icon' => 'droplets',
        'image' => '',
        'price' => 6800,
        'oldPrice' => null,
        'badge' => 'new',
        'desc' => 'Mel 100% natural e orgânico, colhido nos apiários das terras altas angolanas. Rico em vitamina C e antioxidantes.',
        'origin' => 'Bié',
        'rating' => 4.8,
        'reviews' => 74,
    ],
    [
        'id' => 3,
        'name' => 'Cerveja Cuca Original',
        'category' => 'bebidas',
        'icon' => 'beer',
        'image' => '',
        'price' => 1200,
        'oldPrice' => null,
        'badge' => null,
        'desc' => 'A cerveja mais icónica de Angola. Produzida desde 1952, com um sabor refrescante e inconfundível.',
        'origin' => 'Luanda',
        'rating' => 4.7,
        'reviews' => 312,
    ],
    [
        'id' => 4,
        'name' => 'Sumo de Múcua Natural',
        'category' => 'bebidas',
        'icon' => 'cup-soda',
        'image' => '',
        'price' => 950,
        'oldPrice' => null,
        'badge' => 'new',
        'desc' => 'Sumo extraído do fruto do baobá angolano. Rico em vitamina C, cálcio e fibra. 100% natural.',
        'origin' => 'Malanje',
        'rating' => 4.6,
        'reviews' => 56,
    ],
    [
        'id' => 5,
        'name' => 'Máscara Tradicional Cokwe',
        'category' => 'artesanato',
        'icon' => 'mask',
        'image' => '',
        'price' => 35000,
        'oldPrice' => null,
        'badge' => null,
        'desc' => 'Máscara esculpida à mão por artesãos Cokwe do Moxico. Feita em madeira local com pigmentos naturais.',
        'origin' => 'Moxico',
        'rating' => 5.0,
        'reviews' => 22,
    ],
    [
        'id' => 6,
        'name' => 'Cesta Artesanal de Palmeira',
        'category' => 'artesanato',
        'icon' => 'shopping-basket',
        'image' => '',
        'price' => 8500,
        'oldPrice' => 10000,
        'badge' => 'promo',
        'desc' => 'Cesta tradicional tecida à mão com folhas de palmeira. Ideal para decoração ou mercado.',
        'origin' => 'Benguela',
        'rating' => 4.5,
        'reviews' => 88,
    ],
    [
        'id' => 7,
        'name' => 'Óleo de Palma Vermelho',
        'category' => 'agricultura',
        'icon' => 'droplet',
        'image' => '',
        'price' => 3200,
        'oldPrice' => null,
        'badge' => null,
        'desc' => 'Óleo de palma extraído a frio, 100% natural. Essencial na culinária angolana.',
        'origin' => 'Cabinda',
        'rating' => 4.7,
        'reviews' => 145,
    ],
    [
        'id' => 8,
        'name' => 'Farinha de Mandioca (Fuba)',
        'category' => 'alimentacao',
        'icon' => 'wheat',
        'image' => '',
        'price' => 2400,
        'oldPrice' => null,
        'badge' => null,
        'desc' => 'Farinha de mandioca de alta qualidade para preparar o funge. Textura fina e seca.',
        'origin' => 'Uíge',
        'rating' => 4.6,
        'reviews' => 203,
    ],
    [
        'id' => 9,
        'name' => 'Capulana Tradicional',
        'category' => 'textil',
        'icon' => 'scissors',
        'image' => '',
        'price' => 7500,
        'oldPrice' => 9000,
        'badge' => 'promo',
        'desc' => 'Pano capulana com padrões tradicionais angolanos. 100% algodão, cores vibrantes.',
        'origin' => 'Luanda',
        'rating' => 4.8,
        'reviews' => 167,
    ],
    [
        'id' => 10,
        'name' => 'Manteiga de Karité Pura',
        'category' => 'cosmetica',
        'icon' => 'flower',
        'image' => '',
        'price' => 5500,
        'oldPrice' => null,
        'badge' => 'new',
        'desc' => 'Manteiga de karité não refinada do Kuando Kubango. Hidratante profundo natural.',
        'origin' => 'Kuando Kubango',
        'rating' => 4.9,
        'reviews' => 91,
    ],
    [
        'id' => 11,
        'name' => 'Ngola Smartphone 4G',
        'category' => 'tecnologia',
        'icon' => 'smartphone',
        'image' => '',
        'price' => 85000,
        'oldPrice' => 95000,
        'badge' => 'promo',
        'desc' => 'Smartphone assembado em Angola. Ecrã 6.5" HD+, câmara tripla 48MP.',
        'origin' => 'Luanda',
        'rating' => 4.3,
        'reviews' => 44,
    ],
    [
        'id' => 12,
        'name' => 'Pimenta Angolana Moída',
        'category' => 'alimentacao',
        'icon' => 'flame',
        'image' => '',
        'price' => 1800,
        'oldPrice' => null,
        'badge' => null,
        'desc' => 'Pimenta seca e moída de variedades locais. Picante e aromática.',
        'origin' => 'Huíla',
        'rating' => 4.5,
        'reviews' => 178,
    ],
];
